MasterDict = {
    "CHARGER_AC_STATUS_1/1": {"data": "017009187D001EFF",
                         "dgn": "1FFCA",
                         "fault ground current": "11",
                         "fault open ground": "11",
                         "fault open neutral": "11",
                         "fault reverse polarity": "11",
                         "frequency": 60.0,
                         "input/output": "00",
                         "input/output definition":                     "xx not real ",
                         "instance": 1,
                         "line": "00",
                         "line definition": 1,
                         "name": "CHARGER_AC_STATUS_1",
                         "rms current":                             "_var02Charger_AC_current",
                         "rms voltage":                             "_var03Charger_AC_voltage",
                         "timestamp":                               "_var01Timestamp"},
    "CHARGER_AC_STATUS_3/1": {"complementary leg": 255,
                         "data": "01FCFFFFFFFF00FF",
                         "dgn": "1FFC8",
                         "harmonic distortion": 0.0,
                         "input/output": "00",
                         "input/output definition":                      "xx not real data _var04",
                         "instance": 1,
                         "line": "00",
                         "line definition": 1,
                         "name": "CHARGER_AC_STATUS_3",
                         "phase status": "1111",
                         "phase status definition": "no data",
                         "reactive power":                            "not used -bad value",  
                         "real power":                              "_var17AC_real_power",   
                         "timestamp": "1672774555.024753",
                         "waveform": "00",
                         "waveform definition": "sine wave"},
    "CHARGER_STATUS/1": {"auto recharge enable": "11",
                    "charge current":                               "_var04Charger_current",
                    "charge current percent of maximum": 0.0,
                    "charge voltage":                               "_var05Charger_voltage",
                    "data": "011201007D0006FF",
                    "default state on power-up": "11",
                    "dgn": "1FFC7",
                    "force charge": 15,
                    "instance": 1,
                    "name": "CHARGER_STATUS",
                    "operating state": 6,
                    "operating state definition":                   "_var06Charger_state",
                    "timestamp": "1672774554.984803"},
    "DC_SOURCE_STATUS_2/1": {"data": "0164FFFFC8FFFFFF",
                        "device priority": 100,
                        "device priority definition": "inverter Charger",
                        "dgn": "1FFFC",
                        "instance": 1,
                        "instance definition": "main house battery bank",
                        "name": "DC_SOURCE_STATUS_2",
                        "source temperature": "n/a",
                        "state of charge": 100.0,
                        "time remaining": 65535,
                        "timestamp": "1672774554.714678"},
    "DM_RV": {"bank select": 15,
           "data": "0542FFFFFFFFFFFF",
           "dgn": "1FECA",
           "dsa": 66,
           "dsa extension": 255,
           "fmi": 31,
           "name": "DM_RV",
           "occurrence count": 127,
           "operating status": "0101",
           "red lamp status":                                       "_var07Red",
           "spn-isb": 255,
           "spn-lsb": 7,
           "spn-msb": 255,
           "timestamp": "1672774552.1052072",
           "yellow lamp status":                                    "_var08Yellow"
	  },
    "INVERTER_AC_STATUS_1/1": {"data": "4170090A7D001EFF",
                          "dgn": "1FFD7",
                          "fault ground current": "11",
                          "fault open ground": "11",
                          "fault open neutral": "11",
                          "fault reverse polarity": "11",
                          "frequency": 60.0,
                          "input/output": "01",
                          "input/output definition":                    "xxx rubbish ",
                          "instance": 1,
                          "line": "00",
                          "line definition": 1,
                          "name": "INVERTER_AC_STATUS_1",
                          "rms current":                            "_var09Invert_AC_current",
                          "rms voltage":                            "_var10Invert_AC_voltage",
                          "timestamp": "1672774554.8647683"},
    "INVERTER_AC_STATUS_3/1": {"complementary leg": 255,
                          "data": "41C02E002D00FFFF",
                          "dgn": "1FFD5",
                          "harmonic distortion": 255,
                          "input/output": "01",
                          "input/output definition":                                  "xxx rubbish ",
                          "instance": 1,
                          "line": "00",
                          "line definition": 1,
                          "name": "INVERTER_AC_STATUS_3",
                          "phase status": "0000",
                          "phase status definition": "no complementary leg",
                          "reactive power":                         "_var11AC_reactive_power",
                          "real power":                             "_var12AC_real_power",
                          "timestamp": "1672774554.824777",
                          "waveform": "00",
                          "waveform definition": "sine wave"},
    "INVERTER_AC_STATUS_4/1": {"bypass mode active": "11",
                          "data": "4100FFFFFFFFFFFF",
                          "dgn": "1FF8F",
                          "fault high frequency": "11",
                          "fault how frequency": "11",
                          "fault surge protection": "11",
                          "input/output": "01",
                          "input/output definition":                                  " rubbish ",
                          "instance": 1,
                          "line": "00",
                          "line definition": 1,
                          "name": "INVERTER_AC_STATUS_4",
                          "qualification Status": 15,
                          "timestamp": "1672774554.7847886",
                          "voltage fault": 0,
                          "voltage fault definition": "voltage ok"},
    "INVERTER_DC_STATUS/1": {"data": "011201007DFFFFFF",
                        "dc amperage":                              "_var13Invert_DC_Amp",
                        "dc voltage":                               "_var14Invert_DC_Volt",
                        "dgn": "1FEE8",
                        "instance": 1,
                        "name": "INVERTER_DC_STATUS",
                        "timestamp": "1672774554.7448194"},
    "INVERTER_STATUS/1": {"battery temperature sensor present": "00",
                     "battery temperature sensor present definition": "no sensor in use",
                     "data": "0102F0FFFFFFFFFF",
                     "dgn": "1FFD4",
                     "instance": 1,
                     "load sense enabled": "00",
                     "load sense enabled definition": "load sense disabled",
                     "name": "INVERTER_STATUS",
                     "status":                                      "_var16Invert_status_num",
                     "status definition":                           "_var15Invert_status_name",
                     "timestamp": "1672774554.9447553"},
    "INVERTER_TEMPERATURE_STATUS/1": {"data": "01E026FFFFFFFFFF",
                                 "dgn": "1FEBD",
                                 "fet temperature": 38.0,
                                 "fet temperature F": 100.4,
                                 "instance": 1,
                                 "name": "INVERTER_TEMPERATURE_STATUS",
                                 "timestamp": "1672774554.9047515",
                                 "transformer temperature": "n/a"},
    "UNKNOWN-0EEFF": {"data": "ED5FE40E08813C80",
                   "dgn": "0EEFF",
                   "name": "UNKNOWN-0EEFF",
                   "timestamp": "1672774554.1447444"},
    "BATTERY_STATUS/1":{                         
                    "instance":1,
                    "name":"BATTERY_STATUS",
                    "DC_voltage":                                   "_var18Batt_voltage",
                    "DC_current":                                   "_var19Batt_current",
                    "State_of_charge":                              "_var20Batt_charge",
                    "Status":                                                    "",
                    "timestamp":                                    "1672774554.8647683"},
    "ATS_AC_STATUS_1/1": {"data": "4170090A7D001EFF",
                    "dgn": "1FFAD",
                    "instance": 1,
                    "line":                                         "_var21ATS_Line",
                    "line definition": 1,
                    "name": "ATS_AC_STATUS_1",
                    "rms current":                                  "_var22ATS_AC_current",
                    "rms voltage":                                  "_var23ATS_AC_voltage",
                    "timestamp": "1672774554.8647683"},
                     
    "SOLAR_CONTROLLER_STATUS/1":{ 
                    "instance":1,
                    "name":"SOLAR_CONTROLLER_STATUS",
                    "VPV":                                   "_var26Solar_voltage",
                    "PPW":                                   "_var27Solar_power",
                    "V":                                     "_var40Solar_VBatt",
                    "I":                                     "_var41Solar_IBatt",
                    "IL":                                    "_var42Solar_ILoad",
                    "CS":                                    "_var43Solar_charger_Status",
                    "MPPT":                                  "_var44Solar_MPPT_Status",
                    "ERR":                                   "_var45Solar_ERR_Status",
                    "timestamp": "1672774554.8647683"},
    "TANK_STATUS/0": {"absolute level": 65535,
                    "data": "001020FFFFFFFFFF",
                    "dgn": "1FFB7",
                    "instance": 0,
                    "instance definition":                          "_var28Tank_Name",
                    "name": "TANK_STATUS",
                    "relative level":                               "_var29Tank_Level",
                    "resolution":                                   "_var30Tank_Resolution",
                    "tank size": 65535,
                    "timestamp": "1688685071.9489293"},
    "TANK_STATUS/1": {"absolute level": 65535,
                    "data": "010A38FFFFFFFFFF",
                    "dgn": "1FFB7",
                    "instance": 1,
                    "instance definition":                          "_var31Tank_Name",
                    "name": "TANK_STATUS",
                    "relative level":                               "_var32Tank_Level",
                    "resolution":                                   "_var33Tank_Resolution",
                    "tank size": 65535,
                    "timestamp": "1688685072.9491377"},
    "TANK_STATUS/2": {"absolute level": 65535,
                    "data": "020B38FFFFFFFFFF",
                    "dgn": "1FFB7",
                    "instance": 2,
                    "instance definition":                          "_var34Tank_Name",
                    "name": "TANK_STATUS",
                    "relative level":                               "_var35Tank_Level",
                    "resolution":                                   "_var36Tank_Resolution",
                    "tank size": 65535,
                    "timestamp": "1688685071.9494853"},
    "TANK_STATUS/3": {"absolute level": 65535,
                    "data": "034D64FFFFFFFFFF",
                    "dgn": "1FFB7",
                    "instance": 3,
                    "instance definition":                          "_var37Tank_Name",
                    "name": "TANK_STATUS",
                    "relative level":                               "_var38Tank_Level",
                    "resolution":                                   "_var39Tank_Resolution",
                    "tank size": 65535,
                    "timestamp": "1688685071.6974237"},
    "RV_Loads/1": {
                    "instance": 1,
                    "name": "RV_Loads",
                    "AC Load":                                      "_var24RV_Loads_AC",
                    "DC Load":                                      "_var25RV_Loads_DC",
                    "timestamp": "1672774554.8647683"}
}
